execute pathogen#infect()
syntax on
filetype plugin indent on

" Customization
let mapleader=','
set number
set tabstop=2
set shiftwidth=2
set expandtab

" FZF
set rtp+=/usr/local/opt/fzf

" convert tabs to spaces
set expandtab

" use visual cue instead of beep
set visualbell

" dark background
set background=dark

" indicates fast terminal connection (good ole backwards compatibility)
set ttyfast

" saves undo history to file - maybe useful for buffers
set undofile

" case insensitive search unless uppercase character
set ignorecase
set smartcase

" always replace globally
set gdefault

" incremental searching
set incsearch

" Show invisible (tab and end-of-line) characters
set list
set listchars=tab:▸\ ,eol:¬

" fzf & ripgrep config
" https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2
" --column: Show column number
" --line-number: Show line number
" --no-heading: Do not show file headings in results
" --fixed-strings: Search term as a literal string
" --ignore-case: Case insensitive search
" --no-ignore: Do not respect .gitignore, etc...
" --hidden: Search hidden files and folders
" --follow: Follow symlinks
" --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
" --color: Search color options
command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>), 1, <bang>0)

set grepprg=rg\ --vimgrep

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Save behavior
" save on focus lost
autocmd BufLeave,FocusLost * silent! wall

" Allow undo after writing
if has('persistent_undo')      "check if your vim version supports it
    set undofile                 "turn on the feature
    set undodir=$HOME/.vim/undo  "directory where the undo files will be stored
endif

" FZF Key mappings
map <C-p> :GFiles<CR>
map <Leader>b :Buffers<CR>

" Zenburn
set t_Co=256
colors zenburn

" keep visual selection selected when indenting
vnoremap < <gv
vnoremap > >gv
